export const authActionTypes = {
  SHOW_ERROR: ' SHOW_ERROR',
  CHANGE_ANIMATION: 'CHANGE_LOGIN_ANIMATION',
  CHANGE_FORM: 'CHANGE_FORM',
};

export const userDetailsActionTypes = {
  SET_USER_ID: 'SET_USER_ID',
  CHANGE_USER_NAME: 'CHANGE_USER_NAME',
  CHANGE_USER_BIO: 'CHANGE_USER_BIO',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PHONE_NUMBER: 'CHANGE_PHONE_NUMBER',
  CHANGE_BIRTH_DATE: 'CHANGE_BIRTH_DATE',
  CHANGE_GENDER: 'CHANGE_GENDER',
  CHANGE_PROFILE_PICTUE: 'CHANGE_PROFILE_PICTUE',
  CHANGE_ADDRESS: 'CHANGE_ADDRESS',
  CHANGE_COMPANY: 'CHANGE_COMPANY',
};

export const utilsActionTypes = {
  CHANGE_THEME: 'CHANGE_THEME',
  SET_LOADING: 'SET_LOADING',
  SET_TOKEN: 'SET_TOKEN',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
  SHOW_PROFILE_EDIT_MODAL: ' SHOW_PROFILE_EDIT_MODAL',
  SELECT_IMAGE: 'SELECT_IMAGE',
};
